### PR TITLE
Enhancements

### PR DESCRIPTION
**Pull request by ashucg**
All colors are now moved to CSS, classes are updated using JS to allow using different colors for light and dark modes. Updated colors also have better readability because of better contrast ratio. Changes are mostly made for dark theme.
## Current popup
image
image

## Updated popup
image
image

## Icons
Updated font is easier to read (at least for me):

image

### CODE REVIEW

**Comment by d7415** [comment]
I actually prefer the old font face, and I'm not convinced about making the links black - perhaps a darker blue?

The darker text on the 1.2 badge is definitely clearer though. :+1:

**Comment by ashucg** [comment]
Thanks for the feedback. Actually blue over green, orange or red doesn't result in decent contrast ratio (https://contrastchecker.com/) If you have any particular color scheme that looks good and has good accessibility, please share it.

As for the font face, I understand what you mean. Fonts can be really tricky and depends a lot on user preference. It was just an idea I wanted to share because the updated font looked much better and cleaner to me while I was trying it out.

**Comment by rugk** [comment]
I quite like the update.

**Comment by d7415** [comment]
> Thanks for the feedback. Actually blue over green, orange or red doesn't result in decent contrast ratio (https://contrastchecker.com/) If you have any particular color scheme that looks good and has good accessibility, please share it.

Fair point. I'd almost be tempted to lose the cell background for that column and keep it looking different from the rest, but that's probably more controversial than black text!

**Comment by ashucg** [comment]
> Fair point. I'd almost be tempted to lose the cell background for that column and keep it looking different from the rest, but that's probably more controversial than black text!

Yes, I wanted to change background colors as well. But that might not be liked by a lot of users - that's why I decided to try using black color and get some feedback. Another possibile option is to use a greenish/reddish/orangish white for the last column but I haven't tried it yet so I'm not sure how it would look. But it is something that can be tried and since I have already moved to colors to CSS, it is very simple to do so. I will try to share screenshots when I work on it (hopefully tonight)

**Comment by ashucg** [comment]
### Normal / Light
image
### Dark
image

P.S.: I have used red for last row just to see how it would like.

**Comment by ashucg** [comment]
@jannispinter You missed `typeof` operator in your previous commit to fix #45 and I have changed the code a little, that's the only conflict in the updated code. If you want I can submit a separate pull request for it.

**Comment by jannispinter** [comment]
Excellent, thank you so much for your work :+1: 

I've merged this.

**Comment by jannispinter** [comment]
Sorry that it took so long, I'm going to test the new version and if everything is good, release it as v0.3 today. :rocket:

**Comment by ashucg** [comment]
no problem! let me know if you find any issues.

**Comment by andreldmonteiro** [comment]
Please revert the icons, I find them now quite ugly.

**Comment by 532910** [comment]
strike-outs look ugly
bold font looks ugly

**Comment by ashucg** [comment]
please let me know if you have any particular font in mind - which looks good and is easy to read.

**Comment by ashucg** [comment]
[Noto Serif](https://fonts.google.com/specimen/Noto+Serif?preview.text=1.0+1.1+1.2+1.3&preview.text_type=custom#standard-styles) might look good. I can try this font instead but would like to get other recommendations as well.

**Comment by 532910** [comment]
strike-outs are inaccurate and get out of the background

**Comment by 532910** [comment]
red strikeout on red background looks bad

**Comment by andreldmonteiro** [comment]
I liked the icons more in the beginning when they were simpler and TLS 1.2 was green

**Comment by 532910** [comment]
Subpixel rendering looks blurry.

**Pull request merged**
